export const LOGIN = "LOGIN"
export const SIGN = "SIGN"
export const ORDER = "ORDER"

export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_USER = "GET_USER"
export const CHANGE_ROLE = "CHANGE_ROLE"
export const GET_CURRENT_USER="GET_CURRENT_USER"

export const GET_CATEGORYS = "GET_CATEGORYS"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const GET_CATEGORY = "GET_CATEGORY"


export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT"

export const GET_SUPLIERS = "GET_SUPLIERS"
export const GET_SUPLIER = "GET_SUPLIER"
export const CREATE_SUPLIER = "CREATE_SUPLIER"
export const DELETE_SUPLIER = "DELETE_SUPLIER"
export const GET_PRODUCT_SUPLIER = "GET_PRODUCT_SUPLIER"
export const SEARCH_SUPLIER = "SEARCH_SUPLIER"

export const CREATE_ORDER_SUPIER = "CREATE_ORDER_SUPIER"
export const GET_ORDERS_SUPLIER = "GET_ORDERS_SUPLIER"
export const GET_DETAIL_ORDER_SUPLIER = "GET_DETAIL_ORDER_SUPLIER"
export const DETELE_ORDER_SUPLIER = "DETELE_ORDER_SUPLIER"

export const GET_ORDER_CUSTOMERS = "GET_ORDER_CUSTOMERS" 
export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDER = "GET_ORDER"

export const COUNT_CARTS = "COUNT_CARTS"
export const TOTAL_PRICE = "TOTAL_PRICE"

export const GET_FAVORITE_PRODUCTS ="GET_FAVORITE_PRODUCTS"

export const SUCCESS ="SUCCESS"
export const FAIL ="FAIL"

export const PRICEANDINVENTORYALL = "PRICEANDINVENTORYALL"










